In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [81]:
fifa = pd.read_csv( r"C:\Users\hp\OneDrive\Documents\Ashesi\Year 2_Sem 2\Introduction to AI\Fifa\male_players (legacy).csv",low_memory=False)
fifa

player_id                                        player_url  \
0          158023                /player/158023/lionel-messi/150002   
1           20801  /player/20801/c-ronaldo-dos-santos-aveiro/150002   
2            9014                  /player/9014/arjen-robben/150002   
3           41236           /player/41236/zlatan-ibrahimovic/150002   
4          167495                /player/167495/manuel-neuer/150002   
...           ...                                               ...   
161578     269011                   /player/269011/ziye-zhao/230002   
161579     269019                   /player/269019/junjie-wu/230002   
161580     271093               /player/271093/kailin-barlow/230002   
161581     271555               /player/271555/gideon-tetteh/230002   
161582     271608           /player/271608/aqeel-al-dhafeeri/230002   

        fifa_version  fifa_update fifa_update_date         short_name  \
0                 15            2       2014-09-18           L. Messi   
1                 15            2       2014-09-18  Cristiano Ronaldo   
2                 15            2       2014-09-18          A. Robben   
3                 15            2       2014-09-18     Z. Ibrahimović   
4                 15            2       2014-09-18           M. Neuer   
...              ...          ...              ...                ...   
161578            23            2       2022-09-26          Zhao Ziye   
161579            23            2       2022-09-26          Wu Junjie   
161580            23            2       2022-09-26          K. Barlow   
161581            23            2       2022-09-26          G. Tetteh   
161582            23            2       2022-09-26     A. Al Dhafeeri   

                                  long_name player_positions  overall  \
0            Lionel Andrés Messi Cuccittini               CF       93   
1       Cristiano Ronaldo dos Santos Aveiro           LW, LM       92   
2                              Arjen Robben       RM, LM, RW       90   
3                        Zlatan Ibrahimović               ST       90   
4                        Manuel Peter Neuer               GK       90   
...                                     ...              ...      ...   
161578                                  赵梓业               RW       46   
161579                                  吴俊杰               LB       46   
161580                        Kailin Barlow              CDM       46   
161581                        Gideon Tetteh           RW, LW       46   
161582                    Aqeel Al Dhafeeri               CB       46   

        potential  ...   cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  \
0              95  ...  62+3  62+3  62+3  54+3  45+3  45+3  45+3  54+3  15+3   
1              92  ...  63+3  63+3  63+3  57+3  52+3  52+3  52+3  57+3  16+3   
2              90  ...  64+3  64+3  64+3  55+3  46+3  46+3  46+3  55+3  14+3   
3              90  ...  65+3  65+3  61+3  56+3  55+3  55+3  55+3  56+3  17+3   
4              90  ...  40+3  40+3  36+3  36+3  38+3  38+3  38+3  36+3  87+3   
...           ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
161578         61  ...  32+2  32+2  37+2  36+2  31+2  31+2  31+2  36+2  14+2   
161579         58  ...  41+2  41+2  43+2  44+2  48+2  48+2  48+2  44+2  15+2   
161580         58  ...  45+2  45+2  47+2  47+2  46+2  46+2  46+2  47+2  14+2   
161581         70  ...  30+2  30+2  34+2  32+2  28+2  28+2  28+2  32+2  15+2   
161582         63  ...  40+2  40+2  39+2  41+2  46+2  46+2  46+2  41+2  13+2   

                                          player_face_url  
0       https://cdn.sofifa.net/players/158/023/15_120.png  
1       https://cdn.sofifa.net/players/020/801/15_120.png  
2       https://cdn.sofifa.net/players/009/014/15_120.png  
3       https://cdn.sofifa.net/players/041/236/15_120.png  
4       https://cdn.sofifa.net/players/167/495/15_120.png  
...                                                   ...  
161578  https://cdn.

1: DATA PREPERATION

In [29]:
#Removing spaces

In [30]:
for col in fifa:
    if fifa[col].isnull().mean()>0.2:
        fifa.drop(columns=col,inplace=True)

In [31]:
L=[]
L_less=[]
for i in fifa.columns:
  if((fifa[i].isnull().sum())<(0.4*(fifa.shape[0]))):
    L.append(i)
  else:
    L_less.append(i)

In [32]:
L_less #There is no empty columns

[]

In [33]:
numeric_data=fifa.select_dtypes(include=np.number)
non_numeric=fifa.select_dtypes(include = ['object'])

In [34]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 58 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   player_id                       161583 non-null  int64  
 1   fifa_version                    161583 non-null  int64  
 2   fifa_update                     161583 non-null  int64  
 3   overall                         161583 non-null  int64  
 4   potential                       161583 non-null  int64  
 5   value_eur                       159530 non-null  float64
 6   wage_eur                        159822 non-null  float64
 7   age                             161583 non-null  int64  
 8   height_cm                       161583 non-null  int64  
 9   weight_kg                       161583 non-null  int64  
 10  league_id                       159810 non-null  float64
 11  league_level                    158866 non-null  float64
 12  club_team_id    

In [35]:
non_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 43 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   player_url        161583 non-null  object
 1   fifa_update_date  161583 non-null  object
 2   short_name        161583 non-null  object
 3   long_name         161583 non-null  object
 4   player_positions  161583 non-null  object
 5   dob               161583 non-null  object
 6   league_name       159810 non-null  object
 7   club_name         159810 non-null  object
 8   club_position     159810 non-null  object
 9   club_joined_date  150272 non-null  object
 10  nationality_name  161583 non-null  object
 11  preferred_foot    161583 non-null  object
 12  work_rate         161583 non-null  object
 13  body_type         161583 non-null  object
 14  real_face         161583 non-null  object
 15  ls                161583 non-null  object
 16  st                161583 non-null  obj

In [36]:
#Extract data
stats=pd.concat([numeric_data.iloc[:,3:7],numeric_data.iloc[:,17:]],axis=1)
catstats=pd.concat([non_numeric.iloc[:,7:9],non_numeric.iloc[:,12:14]],axis=1)

In [37]:
#Imputing data
from numpy import datetime64, float64, int64 
from sklearn.pipeline import Pipeline, make_pipeline 
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer

catPipe = Pipeline([("impute", SimpleImputer(strategy="most_frequent"))])
fullPipe2= ColumnTransformer ([("cat", catPipe, make_column_selector(dtype_include=object))])
piped2 = fullPipe2.fit_transform(catstats) 
catstats= pd.DataFrame(data=piped2, columns=fullPipe2.get_feature_names_out())
catstats

cat__club_name cat__club_position cat__work_rate  \
0              FC Barcelona                 CF     Medium/Low   
1            Real Madrid CF                 LW       High/Low   
2         FC Bayern München                SUB       High/Low   
3       Paris Saint-Germain                 ST     Medium/Low   
4         FC Bayern München                 GK  Medium/Medium   
...                     ...                ...            ...   
161578           Hebei CFFC                RES  Medium/Medium   
161579        Guangzhou R&F                RES  Medium/Medium   
161580         Sligo Rovers                RES    High/Medium   
161581      Shamrock Rovers                RES  Medium/Medium   
161582             Al Batin                RES  Medium/Medium   

          cat__body_type  
0          Normal (170-)  
1          Normal (185+)  
2       Normal (170-185)  
3          Normal (185+)  
4          Normal (185+)  
...                  ...  
161578    Lean (170-185)  
161579     Normal (185+)  
161580  Normal (170-185)  
161581  Normal (170-185)  
161582    Lean (170-185)  

[161583 rows x 4 columns]

In [38]:
quantPipe = Pipeline([ ("impute", SimpleImputer(strategy="median")) ])
fullPipe1= ColumnTransformer ([("quant", quantPipe, make_column_selector (dtype_include=[float64, int64]))])
piped1 = fullPipe1.fit_transform(stats) 
stats= pd.DataFrame(data=piped1, columns=fullPipe1.get_feature_names_out())
stats

quant__overall  quant__potential  quant__value_eur  quant__wage_eur  \
0                 93.0              95.0       100500000.0         550000.0   
1                 92.0              92.0        79000000.0         375000.0   
2                 90.0              90.0        54500000.0         275000.0   
3                 90.0              90.0        52500000.0         275000.0   
4                 90.0              90.0        63500000.0         300000.0   
...                ...               ...               ...              ...   
161578            46.0              61.0          110000.0            700.0   
161579            46.0              58.0          110000.0            750.0   
161580            46.0              58.0          110000.0            500.0   
161581            46.0              70.0          150000.0            500.0   
161582            46.0              63.0          110000.0            500.0   

        quant__skill_moves  quant__international_reputation  quant__pace  \
0                      4.0                              5.0         93.0   
1                      5.0                              5.0         93.0   
2                      4.0                              5.0         93.0   
3                      4.0                              5.0         76.0   
4                      1.0                              5.0         69.0   
...                    ...                              ...          ...   
161578                 2.0                              1.0         63.0   
161579                 2.0                              1.0         55.0   
161580                 2.0                              1.0         65.0   
161581                 2.0                              1.0         55.0   
161582                 2.0                              1.0         61.0   

        quant__shooting  quant__passing  quant__dribbling  ...  \
0                  89.0            86.0              96.0  ...   
1                  93.0            81.0              91.0  ...   
2                  86.0            83.0              92.0  ...   
3                  91.0            81.0              86.0  ...   
4                  54.0            58.0              63.0  ...   
...                 ...             ...               ...  ...   
161578             48.0            40.0              47.0  ...   
161579             25.0            29.0              34.0  ...   
161580             36.0            43.0              46.0  ...   
161581             50.0            36.0              46.0  ...   
161582             22.0            26.0              32.0  ...   

        quant__mentality_vision  quant__mentality_penalties  \
0                          90.0                        76.0   
1                          81.0                        85.0   
2                          84.0                        80.0   
3                          83.0                        91.0   
4                          20.0                        37.0   
...                         ...                         ...   
161578                     42.0                        54.0   
161579                     31.0                        31.0   
161580                     40.0                        37.0   
161581                     44.0                        63.0   
161582                     20.0                        25.0   

        quant__defending_marking_awareness  quant__defending_standing_tackle  \
0                                     25.0                              21.0   
1                                     22.0                              31.0   
2                                     29.0                              26.0   
3                                     25.0                              41.0   
4                                     25.0                              25.0   
...                                    ...                               ...   
161578                              

In [39]:
catstats.columns

Index(['cat__club_name', 'cat__club_position', 'cat__work_rate',
       'cat__body_type'],
      dtype='object')

In [40]:
#encoding data
from numpy import array
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(catstats['cat__club_name'])
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)

encodedcat=pd.DataFrame(integer_encoded, columns=['cat__club_name'])

label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(catstats['cat__club_position'])
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
encodedcat['cat__club_position']=integer_encoded

label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(catstats['cat__work_rate'])
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
encodedcat['cat__work_rate']=integer_encoded

label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(catstats['cat__body_type'])
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
encodedcat['cat__body_type']=integer_encoded

encodedcat

cat__club_name  cat__club_position  cat__work_rate  cat__body_type
0                  478                   3               7               3
1                 1013                  14               1               5
2                  481                  28               1               4
3                  947                  27               7               5
4                  481                   5               8               5
...                ...                 ...             ...             ...
161578             663                  21               8               1
161579             633                  21               8               5
161580            1165                  21               2               4
161581            1139                  21               8               4
161582              64                  21               8               1

[161583 rows x 4 columns]

In [41]:
data=pd.concat([stats,encodedcat],axis=1).reset_index(drop=True)
data

quant__overall  quant__potential  quant__value_eur  quant__wage_eur  \
0                 93.0              95.0       100500000.0         550000.0   
1                 92.0              92.0        79000000.0         375000.0   
2                 90.0              90.0        54500000.0         275000.0   
3                 90.0              90.0        52500000.0         275000.0   
4                 90.0              90.0        63500000.0         300000.0   
...                ...               ...               ...              ...   
161578            46.0              61.0          110000.0            700.0   
161579            46.0              58.0          110000.0            750.0   
161580            46.0              58.0          110000.0            500.0   
161581            46.0              70.0          150000.0            500.0   
161582            46.0              63.0          110000.0            500.0   

        quant__skill_moves  quant__international_reputation  quant__pace  \
0                      4.0                              5.0         93.0   
1                      5.0                              5.0         93.0   
2                      4.0                              5.0         93.0   
3                      4.0                              5.0         76.0   
4                      1.0                              5.0         69.0   
...                    ...                              ...          ...   
161578                 2.0                              1.0         63.0   
161579                 2.0                              1.0         55.0   
161580                 2.0                              1.0         65.0   
161581                 2.0                              1.0         55.0   
161582                 2.0                              1.0         61.0   

        quant__shooting  quant__passing  quant__dribbling  ...  \
0                  89.0            86.0              96.0  ...   
1                  93.0            81.0              91.0  ...   
2                  86.0            83.0              92.0  ...   
3                  91.0            81.0              86.0  ...   
4                  54.0            58.0              63.0  ...   
...                 ...             ...               ...  ...   
161578             48.0            40.0              47.0  ...   
161579             25.0            29.0              34.0  ...   
161580             36.0            43.0              46.0  ...   
161581             50.0            36.0              46.0  ...   
161582             22.0            26.0              32.0  ...   

        quant__defending_sliding_tackle  quant__goalkeeping_diving  \
0                                  20.0                        6.0   
1                                  23.0                        7.0   
2                                  26.0                       10.0   
3                                  27.0                       13.0   
4                                  25.0                       87.0   
...                                 ...                        ...   
161578                             25.0                        9.0   
161579                             45.0                        6.0   
161580                             50.0                        8.0   
161581                             14.0                       13.0   
161582                             42.0                       13.0   

        quant__goalkeeping_handling  quant__goalkeeping_kicking  \
0                              11.0                        15.0   
1                              11.0                        15.0   
2                               8.0                        11.0   
3                              15.0                        10.0   
4                              85.0                        92.0   
...                             ...                         ...   
161578                         13.0        

2: CORRELATION

In [42]:
corr_matrix=data.corr()
finalcorr=corr_matrix['quant__overall'].sort_values(ascending=False)
print(finalcorr)

quant__overall                        1.000000
quant__movement_reactions             0.845753
quant__potential                      0.695362
quant__passing                        0.629868
quant__wage_eur                       0.607297
quant__value_eur                      0.562677
quant__dribbling                      0.561034
quant__attacking_short_passing        0.499757
quant__mentality_vision               0.493282
quant__international_reputation       0.485234
quant__skill_long_passing             0.483808
quant__power_shot_power               0.480297
quant__physic                         0.473469
quant__skill_ball_control             0.457011
quant__shooting                       0.444746
quant__skill_curve                    0.415863
quant__power_long_shots               0.409086
quant__mentality_aggression           0.398310
quant__attacking_crossing             0.396833
quant__skill_fk_accuracy              0.387269
quant__attacking_volleys              0.377048
quant__skill_

In [43]:
#The following features that contribute reletively significantly to the overal score are: quant__movement_reactions, quant__potential,quant__passing,quant__wage_eur,quant__value_eur,quant__dribbling

In [44]:
finaldata=data[['quant__movement_reactions', 'quant__potential','quant__passing','quant__wage_eur','quant__value_eur','quant__dribbling']]
finaldata

quant__movement_reactions  quant__potential  quant__passing  \
0                            94.0              95.0            86.0   
1                            90.0              92.0            81.0   
2                            89.0              90.0            83.0   
3                            85.0              90.0            81.0   
4                            89.0              90.0            58.0   
...                           ...               ...             ...   
161578                       39.0              61.0            40.0   
161579                       42.0              58.0            29.0   
161580                       50.0              58.0            43.0   
161581                       45.0              70.0            36.0   
161582                       40.0              63.0            26.0   

        quant__wage_eur  quant__value_eur  quant__dribbling  
0              550000.0       100500000.0              96.0  
1              375000.0        79000000.0              91.0  
2              275000.0        54500000.0              92.0  
3              275000.0        52500000.0              86.0  
4              300000.0        63500000.0              63.0  
...                 ...               ...               ...  
161578            700.0          110000.0              47.0  
161579            750.0          110000.0              34.0  
161580            500.0          110000.0              46.0  
161581            500.0          150000.0              46.0  
161582            500.0          110000.0              32.0  

[161583 rows x 6 columns]

3:TRAINING AND TESTING

In [45]:
#defining variables
y=stats['quant__overall']

In [46]:
X=finaldata

In [47]:
y

0         93.0
1         92.0
2         90.0
3         90.0
4         90.0
          ... 
161578    46.0
161579    46.0
161580    46.0
161581    46.0
161582    46.0
Name: quant__overall, Length: 161583, dtype: float64

In [48]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
X

array([[ 3.53577452,  3.87531516,  2.92656997, 24.69710444, 16.44742817,
         3.48048741],
       [ 3.09957117,  3.39601316,  2.42100822, 16.68182522, 12.84617746,
         2.96586642],
       [ 2.99052033,  3.0764785 ,  2.62323292, 12.10166567,  8.74242665,
         3.06879062],
       ...,
       [-1.26246241, -2.0360761 , -1.42126106, -0.47087231, -0.36790015,
        -1.66572251],
       [-1.8077166 , -0.11886813, -2.12904751, -0.47087231, -0.36120015,
        -1.66572251],
       [-2.3529708 , -1.23723945, -3.140171  , -0.47087231, -0.36790015,
        -3.10666128]])

In [49]:
#Models

In [50]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
!pip install xgboost
from xgboost import XGBRegressor

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score, auc
import pickle as pkl

In [26]:
rf=RandomForestClassifier(n_estimators=100)
gb=GradientBoostingClassifier(n_estimators=100)
xgb=XGBRegressor(n_estimators=100)

In [29]:
for model in (rf,gb):
 model.fit(Xtrain, Ytrain)
 pkl.dump(model, open('FIFA Assignment.ipynb' + model.__class__.__name__ + '.pkl', 'wb'))
 y_pred = model.predict(Xtest)
 print(model.__class__.__name__, confusion_matrix(Ytest, y_pred), classification_report(Ytest, y_pred))

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.

RandomForestClassifier [[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]]               precision    recall  f1-score   support

        40.0       0.00      0.00      0.00         1
        41.0       0.00      0.00      0.00         0
        42.0       0.00      0.00      0.00         1
        43.0       0.00      0.00      0.00         1
        44.0       0.00      0.00      0.00         4
        45.0       0.00      0.00      0.00         7
        46.0       0.25      0.20      0.22        15
        47.0       0.17      0.12      0.14        40
        48.0       0.25      0.16      0.19        76
        49.0       0.34      0.31      0.32       120
        50.0       0.43      0.45      0.44       211
        51.0       0.48      0.51      0.50       265
        52.0       0.52      0.56      0.54       361
        53.0       0.48      0.43      0.46       423
        54.0       0.49      0.50      0.50   

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


GradientBoostingClassifier [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]               precision    recall  f1-score   support

        40.0       0.00      0.00      0.00         1
        42.0       0.00      0.00      0.00         1
        43.0       0.00      0.00      0.00         1
        44.0       0.00      0.00      0.00         4
        45.0       0.00      0.00      0.00         7
        46.0       0.00      0.00      0.00        15
        47.0       0.00      0.00      0.00        40
        48.0       0.00      0.00      0.00        76
        49.0       0.11      0.03      0.05       120
        50.0       0.30      0.39      0.34       211
        51.0       0.25      0.43      0.32       265
        52.0       0.34      0.37      0.36       361
        53.0       0.35      0.27      0.30       423
        54.0       0.27      0.33      0.30       486
        55.0       0.37      0.28      0.3

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [34]:
#Between the two models Random Forest Classifier is more accurate

In [35]:
#Cross Validation

In [8]:
from sklearn.model_selection import KFold, cross_val_score

In [37]:
kfolds=2
for model in (rf,gb,xgb):
    cvscores=cross_val_score(model,X,y,cv=kfolds)
    print(model)
    print('CV Score',cvscores)
    print('Average Score',cvscores.mean())

RandomForestClassifier()
CV Score [0.42845826 0.38057457]
Average Score 0.40451641607194366
GradientBoostingClassifier()
CV Score [0.37072978 0.37394017]
Average Score 0.37233497091399276
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)
CV Score [0.91055894 0.84400852]
Average Score 0.8772837316708091


In [ ]:
#XGB Regressor has the best score

4:PERFORMANCE

In [39]:
for model in (rf,xgb):
    model.fit(Xtrain,Ytrain)
    from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score
    y_pred=model.predict(Xtest)
    print(model,f"""Mean Absolute Error={mean_absolute_error(y_pred,Ytest)},
        Mean Squared Error={mean_squared_error(y_pred,Ytest)},
        Root Mean Squared Error={np.sqrt(mean_squared_error(y_pred,Ytest))},
        R2 Score={r2_score(y_pred,Ytest)}""")

Mean Absolute Error=0.9047250673020392,
        Mean Squared Error=3.2272178729461274,
        Root Mean Squared Error=1.7964459003672022,
        R2 Score=0.9337363595434893
Mean Absolute Error=1.1620041768466842,
        Mean Squared Error=2.6138733635932936,
        Root Mean Squared Error=1.6167477736472358,
        R2 Score=0.9442447125066754


In [40]:
#Overall XGB regressor has a better performance

In [41]:
#Tuning model **

In [42]:
from sklearn.model_selection import GridSearchCV, KFold

In [ ]:
PARAMETERS_gb ={
"max_depth":[2,5, 6, 12],
"learning_rate":[0.3, 0.1, 0.03],
"n_estimators":[100,500,1000]}

In [ ]:
from sklearn.model_selection import GridSearchCV, KFold
model_gs=GridSearchCV(xgb,param_grid=PARAMETERS_gb,cv=5,scoring="accuracy")
model_gs.fit(Xtrain, Ytrain)
pkl.dump(model_gs, open('Ensemble_Classification.ipynb' + model_gs.__class__.__name__ + '.pkl', 'wb'))
y_pred = model_gs.predict(Xtest)
print(model_gs.__class__.__name__, confusion_matrix(Ytest, y_pred), classification_report(Ytest, y_pred))

In [ ]:
model_gs.best_params_

In [ ]:
model_gs.best_score_

5: players_22 TESTING

In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

In [66]:
players22 = pd.read_csv( r"C:\Users\hp\OneDrive\Documents\Ashesi\Year 2_Sem 2\Introduction to AI\Fifa\players_22-1.csv",low_memory=False)
players22

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1         188545  https://sofifa.com/player/188545/robert-lewand...   
2          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
3         190871  https://sofifa.com/player/190871/neymar-da-sil...   
4         192985  https://sofifa.com/player/192985/kevin-de-bruy...   
...          ...                                                ...   
19234     261962  https://sofifa.com/player/261962/defu-song/220002   
19235     262040  https://sofifa.com/player/262040/caoimhin-port...   
19236     262760  https://sofifa.com/player/262760/nathan-logue/...   
19237     262820  https://sofifa.com/player/262820/luke-rudden/2...   
19238     264540  https://sofifa.com/player/264540/emanuel-lalch...   

               short_name                            long_name  \
0                L. Messi       Lionel Andrés Messi Cuccittini   
1          R. Lewandowski                   Robert Lewandowski   
2       Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   
3               Neymar Jr        Neymar da Silva Santos Júnior   
4            K. De Bruyne                      Kevin De Bruyne   
...                   ...                                  ...   
19234           Song Defu                                  宋德福   
19235           C. Porter                      Caoimhin Porter   
19236            N. Logue              Nathan Logue-Cunningham   
19237           L. Rudden                          Luke Rudden   
19238  E. Lalchhanchhuaha              Emanuel Lalchhanchhuaha   

      player_positions  overall  potential    value_eur  wage_eur  age  ...  \
0           RW, ST, CF       93         93   78000000.0  320000.0   34  ...   
1                   ST       92         92  119500000.0  270000.0   32  ...   
2               ST, LW       91         91   45000000.0  270000.0   36  ...   
3              LW, CAM       91         91  129000000.0  270000.0   29  ...   
4              CM, CAM       91         91  125500000.0  350000.0   30  ...   
...                ...      ...        ...          ...       ...  ...  ...   
19234              CDM       47         52      70000.0    1000.0   22  ...   
19235               CM       47         59     110000.0     500.0   19  ...   
19236               CM       47         55     100000.0     500.0   21  ...   
19237               ST       47         60     110000.0     500.0   19  ...   
19238              CAM       47         60     110000.0     500.0   19  ...   

        lcb    cb   rcb    rb    gk  \
0      50+3  50+3  50+3  61+3  19+3   
1      60+3  60+3  60+3  61+3  19+3   
2      53+3  53+3  53+3  60+3  20+3   
3      50+3  50+3  50+3  62+3  20+3   
4      69+3  69+3  69+3  75+3  21+3   
...     ...   ...   ...   ...   ...   
19234  46+2  46+2  46+2  48+2  15+2   
19235  44+2  44+2  44+2  48+2  14+2   
19236  45+2  45+2  45+2  47+2  12+2   
19237  26+2  26+2  26+2  32+2  15+2   
19238  41+2  41+2  41+2  45+2  16+2   

                                         player_face_url  \
0      https://cdn.sofifa.net/players/158/023/22_120.png   
1      https://cdn.sofifa.net/players/188/545/22_120.png   
2      https://cdn.sofifa.net/players/020/801/22_120.png   
3      https://cdn.sofifa.net/players/190/871/22_120.png   
4      https://cdn.sofifa.net/players/192/985/22_120.png   
...                                                  ...   
19234  https://cdn.sofifa.net/players/261/962/22_120.png   
19235  https://cdn.sofifa.net/players/262/040/22_120.png   
19236  https://cdn.sofifa.net/players/262/760/22_120.png   
19237  https://cdn.sofifa.net/players/262/820/22_120.png   
19238  https://cdn.sofifa.net/players/264/540/22_120.png   

                                    club_logo_url  \
0          https://cdn.sofifa.net/teams/73/60.png   
1          https://cdn.sofifa.net/teams/21/60.png   
2          https://cdn.sofifa.net/teams/11/60.png   
3         

In [67]:
for col in players22 :
    if players22 [col].isnull().mean()>0.2:
        players22 .drop(columns=col,inplace=True)

In [68]:
finalTdata=players22 [['overall','movement_reactions', 'potential','passing','wage_eur','value_eur','dribbling']]
finalTdata

overall  movement_reactions  potential  passing  wage_eur    value_eur  \
0           93                  94         93     91.0  320000.0   78000000.0   
1           92                  93         92     79.0  270000.0  119500000.0   
2           91                  94         91     80.0  270000.0   45000000.0   
3           91                  89         91     86.0  270000.0  129000000.0   
4           91                  91         91     93.0  350000.0  125500000.0   
...        ...                 ...        ...      ...       ...          ...   
19234       47                  53         52     46.0    1000.0      70000.0   
19235       47                  49         59     50.0     500.0     110000.0   
19236       47                  46         55     45.0     500.0     100000.0   
19237       47                  48         60     36.0     500.0     110000.0   
19238       47                  54         60     45.0     500.0     110000.0   

       dribbling  
0           95.0  
1           86.0  
2           88.0  
3           94.0  
4           88.0  
...          ...  
19234       48.0  
19235       46.0  
19236       49.0  
19237       48.0  
19238       48.0  

[19239 rows x 7 columns]

In [69]:
from numpy import datetime64, float64, int64 
from sklearn.pipeline import Pipeline, make_pipeline 
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer
quantPipe = Pipeline([ ("impute", SimpleImputer(strategy="median")) ])
fullPipe= ColumnTransformer ([("quant", quantPipe, make_column_selector (dtype_include=[float64, int64]))])
piped= fullPipe.fit_transform(finalTdata) 
finalTdata= pd.DataFrame(data=piped, columns=fullPipe.get_feature_names_out())
finalTdata

quant__overall  quant__movement_reactions  quant__potential  \
0                93.0                       94.0              93.0   
1                92.0                       93.0              92.0   
2                91.0                       94.0              91.0   
3                91.0                       89.0              91.0   
4                91.0                       91.0              91.0   
...               ...                        ...               ...   
19234            47.0                       53.0              52.0   
19235            47.0                       49.0              59.0   
19236            47.0                       46.0              55.0   
19237            47.0                       48.0              60.0   
19238            47.0                       54.0              60.0   

       quant__passing  quant__wage_eur  quant__value_eur  quant__dribbling  
0                91.0         320000.0        78000000.0              95.0  
1                79.0         270000.0       119500000.0              86.0  
2                80.0         270000.0        45000000.0              88.0  
3                86.0         270000.0       129000000.0              94.0  
4                93.0         350000.0       125500000.0              88.0  
...               ...              ...               ...               ...  
19234            46.0           1000.0           70000.0              48.0  
19235            50.0            500.0          110000.0              46.0  
19236            45.0            500.0          100000.0              49.0  
19237            36.0            500.0          110000.0              48.0  
19238            45.0            500.0          110000.0              48.0  

[19239 rows x 7 columns]

In [70]:
corr_matrix=finalTdata.corr()
finalcorr=finalTdata['quant__overall'].sort_values(ascending=False)
print(finalcorr)

0        93.0
1        92.0
2        91.0
3        91.0
4        91.0
         ... 
19223    47.0
19222    47.0
19221    47.0
19220    47.0
19238    47.0
Name: quant__overall, Length: 19239, dtype: float64


In [71]:
y=finalTdata['quant__overall']
X=finalTdata[1:]

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
X

array([[ 3.8138131 ,  3.49052412,  3.43872729, ..., 13.51546244,
        15.38939807,  2.55581607],
       [ 3.66840995,  3.60115295,  3.27436609, ..., 13.51546244,
         5.56166289,  2.77537791],
       [ 3.66840995,  3.04800881,  3.27436609, ..., 13.51546244,
        16.6425992 ,  3.43406345],
       ...,
       [-2.72932845, -1.7090308 , -2.6426374 , ..., -0.43923604,
        -0.3613614 , -1.50607808],
       [-2.72932845, -1.48777315, -1.82083136, ..., -0.43923604,
        -0.36004224, -1.615859  ],
       [-2.72932845, -0.82400018, -1.82083136, ..., -0.43923604,
        -0.36004224, -1.615859  ]])

In [72]:
y

0        93.0
1        92.0
2        91.0
3        91.0
4        91.0
         ... 
19234    47.0
19235    47.0
19236    47.0
19237    47.0
19238    47.0
Name: quant__overall, Length: 19239, dtype: float64

In [73]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

ValueError: Found input variables with inconsistent numbers of samples: [19238, 19239]

In [74]:
xgb=XGBRegressor(n_estimators=100)

In [76]:
xgbfit(Xtrain,Ytrain)
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score
y_pred=xgb.predict(Xtest)
print(model,f"""Mean Absolute Error={mean_absolute_error(y_pred,Ytest)},
        Mean Squared Error={mean_squared_error(y_pred,Ytest)},
        Root Mean Squared Error={np.sqrt(mean_squared_error(y_pred,Ytest))},
        R2 Score={r2_score(y_pred,Ytest)}""")

NameError: name 'xgbfit' is not defined

6: WEBSITE

In [77]:
import requests
!pip install streamlit
import streamlit as st

In [78]:
streamlit run FIFA Assignment.ipynb

SyntaxError: invalid syntax (1789332086.py, line 1)

In [ ]:
st.title ("Fifa Score Prediction")

In [ ]:
st.movement_reactions('Pick a number', 0,100)
st.potential('Pick a number', 0,100)
st.passing('Pick a number', 0,100)
st.wage_eur('Pick a number', 0,1000000000)
st.value_eur('Pick a number', 0,1000000000)
st.dribbling('Pick a number', 0,100)					

In [ ]:
df=pd.Dataframe('movement_reactions':movement_reactions,'potential':potential,'passing':passing,'wage_eur':wage_eur,'value_eur':value_eur,'dribbling':dribbling)

In [ ]:
X=0

In [ ]:
y=df

In [ ]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
xgb=XGBRegressor(n_estimators=100)

In [ ]:
xgbfit(Xtrain,Ytrain)
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score
y_pred=xgb.predict(Xtest)
print(model,f"""Mean Absolute Error={mean_absolute_error(y_pred,Ytest)},
        Mean Squared Error={mean_squared_error(y_pred,Ytest)},
        Root Mean Squared Error={np.sqrt(mean_squared_error(y_pred,Ytest))},
        R2 Score={r2_score(y_pred,Ytest)}""")